services:
  ollama:
    build:
      context: .
      dockerfile: ollama.dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:11434/api/tags > /dev/null"]
      interval: 15s
      timeout: 10s
      start_period: 10s
      retries: 5


  rag:
    build:
      context: ./ragcontext
      dockerfile: rag.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - app_network

  # similarity:
  #   build:
  #     context: ./similaritycontext
  #     dockerfile: knn.Dockerfile
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app_network

  # frontend:
  #   build:
  #     context: ./http/research-orbits
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app_network

volumes:
  ollama_data:

networks:
  app_network:
    driver: bridge